export const Characteristic = {
    FRIENDLY: { key: "FRIENDLY", label: "Przyjazny" },
    CALM: { key: "CALM", label: "Spokojny" },
    ACTIVE: { key: "ACTIVE", label: "Aktywny" },
    PROTECTIVE: { key: "PROTECTIVE", label: "Opiekuńczy" },
    INTELLIGENT: { key: "INTELLIGENT", label: "Inteligentny" },
    INDEPENDENT: { key: "INDEPENDENT", label: "Niezależny" },
    PLAYFUL: { key: "PLAYFUL", label: "Figlarny" },
    ALERT: { key: "ALERT", label: "Czujny" },
    STUBBORN: { key: "STUBBORN", label: "Uparty" },
    CURIOUS: { key: "CURIOUS", label: "Ciekawski" },
    LOYAL: { key: "LOYAL", label: "Lojalny" },
    GENTLE: { key: "GENTLE", label: "Łagodny" },
    ENERGETIC: { key: "ENERGETIC", label: "Energetyczny" },
    SHY: { key: "SHY", label: "Nieśmiały" },
    CONFIDENT: { key: "CONFIDENT", label: "Pewny siebie" },
};
